site_name: Zendikit School
site_url: https://zendikit.school
site_description: Zendikit educational material
site_author: Zendikit

docs_dir: src
site_dir: docs

nav:
  - Home: 'index.md'
  - Japanese:
      - Grammar:
        - Organization: 'japanese/grammar/organization.md'
        - N5: 'japanese/grammar/n5.md'

theme:
  name: material
  palette:
    primary: white

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/barcode
      link: https://zendikit.work
