site_name: Zendikit School
site_url: https://zendikit.school
site_description: Zendikit educational material
site_author: Zendikit

docs_dir: site
site_dir: docs

nav:
  - Home: 'index.md'
  - Japanese:
      - Grammar:
        - Introduction: 'japanese/grammar/introduction.md'
        - N5: 'japanese/grammar/n5.md'
        - N4: 'japanese/grammar/n4.md'
  - Computer Vision:
    - Learned:
      - Introduction: 'computer_vision/learned/introduction.md'
      - Engine:
        - Skeleton: 'computer_vision/learned/engine/skeleton.md'
        - Skeleton Implementation: 'computer_vision/learned/engine/skeleton_implementation.md'
        - Datasets: 'computer_vision/learned/engine/datasets.md'
        - Dataset Implementation: 'computer_vision/learned/engine/dataset_implementation.md'
        - Dataset Visualization: 'computer_vision/learned/engine/dataset_visualization.md'
        - Dataset Visualization Implementation: 'computer_vision/learned/engine/dataset_visualization_implementation.md'

theme:
  name: material
  palette:
    primary: white

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/barcode
      link: https://zendikit.work
